# Generated by Django 4.1.7 on 2023-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='picture',
            field=models.ImageField(blank=True, upload_to='property_pics'),
        ),
    ]
