# Generated by Django 4.1.7 on 2023-04-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
    ]
