# Generated by Django 4.1.7 on 2023-04-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='property_pictures'),
        ),
    ]
