# Generated by Django 4.1.7 on 2023-04-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, to='property.imagemodel'),
        ),
    ]
