# Generated by Django 4.1.7 on 2023-04-10 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_imagemodel_remove_property_pictures_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='belongs_to',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='main_pic',
            field=models.ImageField(blank=True, upload_to='property_images'),
        ),
    ]
