# Generated by Django 4.1.7 on 2023-04-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_property_images_imagemodel_belongs_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='belongs_to',
            field=models.IntegerField(blank=True),
        ),
    ]
